language: csharp
solution: Battleship.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Battleship.sln
after_script:
  - nunit-console BattleshipTest/bin/Release/BattleshipTest.dll
